# Generated by Django 6.1.1 on 2026-10-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_phone_website_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_products', to='core.contact')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
