# Generated by Django 6.1.1 on 2026-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='tax ID'),
        ),
    ]
