# Generated by Django 6.1.1 on 2026-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='street 2'),
        ),
    ]
