# Generated by Django 6.1.1 on 2026-09-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_street2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Must be a company. Leave blank for a standalone contact.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VAT number, EIN, or local tax identifier — format varies by country.', max_length=100, verbose_name='tax ID'),
        ),
    ]
