# Generated by Django 6.1.1 on 2026-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_parent_alter_contact_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, help_text='International format: + and the country code, then the number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='International format: + and the country code, then the number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, help_text='Full address, starting with https://'),
        ),
    ]
